"""Lazy, provider-neutral adapter ABI.

Importing this package validates no installation metadata, resolves no binary,
and runs no provider probe.  Concrete distributions may expose a
``ProviderAdapterSpecV1`` and build Core plugin metadata only when their entry
point is explicitly loaded.
"""

from .contract import (
    PROVIDER_ADAPTER_ABI_V1,
    AdapterDescriptorV1,
    AdapterServerPolicy,
    AdapterStatus,
    AuthSpec,
    BinarySpec,
    BuiltPromptInvocation,
    DeclarativeProbeSpec,
    DoctorProbeSpec,
    DynamicArgument,
    EnvironmentPolicy,
    ExitStatusProbeSpec,
    FeatureProbeSpec,
    FixedCommandSpec,
    JsonProbeSpec,
    ModelProbeSpec,
    OperationLimits,
    PromptCommandSpec,
    PromptMode,
    PromptSentinelPolicy,
    PlainTextFieldSpec,
    PlainTextProbeSpec,
    ProbeFormat,
    ProviderAdapterSpecV1,
    ProviderCapability,
    TransportKind,
    TransportConfig,
    VersionProbeSpec,
    describe_adapter,
    valid_provider_id,
)
from .registry import ProviderAdapterRegistryV1
from .runtime import (
    AdapterInspectionV1,
    BinaryProvenance,
    InteractiveAuthSessionV1,
    OpenedProcessTransportV1,
    ProtocolLaunchBoundaryV1,
    ProviderAdapterV1,
    drain_pending_cleanups,
)


__all__ = [
    "PROVIDER_ADAPTER_ABI_V1",
    "AdapterDescriptorV1",
    "AdapterInspectionV1",
    "AdapterServerPolicy",
    "AdapterStatus",
    "AuthSpec",
    "BinaryProvenance",
    "BinarySpec",
    "BuiltPromptInvocation",
    "DeclarativeProbeSpec",
    "DoctorProbeSpec",
    "DynamicArgument",
    "EnvironmentPolicy",
    "ExitStatusProbeSpec",
    "FeatureProbeSpec",
    "FixedCommandSpec",
    "InteractiveAuthSessionV1",
    "JsonProbeSpec",
    "ModelProbeSpec",
    "OperationLimits",
    "OpenedProcessTransportV1",
    "PlainTextFieldSpec",
    "PlainTextProbeSpec",
    "PromptCommandSpec",
    "PromptMode",
    "PromptSentinelPolicy",
    "ProbeFormat",
    "ProtocolLaunchBoundaryV1",
    "ProviderAdapterRegistryV1",
    "ProviderAdapterSpecV1",
    "ProviderAdapterV1",
    "ProviderCapability",
    "TransportKind",
    "TransportConfig",
    "VersionProbeSpec",
    "describe_adapter",
    "drain_pending_cleanups",
    "valid_provider_id",
]
